{
 "title": "CIO",
 "description": "OpsTeam",
 "time": { "from": "now-1w", "to": "now-24h" },
 "panels": [
  { "title": "CIO Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\n# CIO Dashboard\n\nDashboard to monitor the CF project\n\n## Custom recording rule\n\nThe team onboarding metrics is using a recording rule behing the scene.\n\n```\n  - name: team1\n    rules:\n      - record: \"onboarded_team\"\n        expr: |\n          count(group by (organization_id) (container_age))-3\n```\n\nThe minus 3 is to remove default orgs (system, p-spring-cloud-services, wavefront-nozzle-org)\n\n\n[documentation](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/)\n\n"
   },
   "content": "\n# Logging and Metrics\n\nThe Logging and Metrics Firehose (also known as Loggregator) helps gather logs and metrics from across the foundation, to be sent to a number of downstream consumers. \n\nThe health of the components below will dictate whether developers can see logs and metrics for their apps, and whether that information will be sent to tools like Healthwatch, App Metrics and external partners.\n\n(Note: this does not affect platform logs sent over syslog.)"
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Team onboarded",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * onboarded_team/15",
     "legendFormat": "percentage of app teams onboarded"
    }
   ]
  },
  {
   "title": "Ticket queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pcf_ticket_opened_total-pcf_ticket_closed_total",
     "legendFormat": "percentage of app teams onboarded"
    }
   ]
  },
  { "title": "Onboarded teams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of dev teams onboarded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "onboarded_team" }
   ]
  },
  {
   "title": "Number of dev teams onboarded (7 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_min(delta(onboarded_team[1w]),0)"
    }
   ]
  },
  {
   "title": "Number of dev teams onboarded (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_min(delta(onboarded_team[4w]),0)"
    }
   ]
  },
  {
   "title": "Number of dev team onboarded",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onboarded_team",
     "legendFormat": "Number of app instances running on the platform, as reported by Diego"
    }
   ]
  },
  { "title": "Tickets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total ticket opened ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pcf_ticket_opened_total" }
   ]
  },
  {
   "title": "Total ticket closed ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pcf_ticket_closed_total" }
   ]
  },
  {
   "title": "Tickets over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pcf_ticket_opened_total", "legendFormat": "opened" },
    { "expr": "pcf_ticket_closed_total", "legendFormat": "closed" }
   ]
  },
  {
   "title": "Number ticket opened (7 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(pcf_ticket_opened_total[1w])"
    }
   ]
  },
  {
   "title": "Number ticket closed (7 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(pcf_ticket_closed_total[1w])"
    }
   ]
  },
  {
   "title": "Number ticket opened (30 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pcf_ticket_opened_total[30d])"
    }
   ]
  },
  {
   "title": "Number ticket closed (30 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pcf_ticket_closed_total[30d])"
    }
   ]
  }
 ]
}